-- GaugePro gallery manifest - generado por dev/gallery.lua
-- No editar a mano. Comparar con:
--   lua5.3 dev/gallery.lua . --baseline <este fichero>
return {
  ["branch"] = "feat/gauge-v2",
  ["cases"] = {
    ["op-mm-mark"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 35,
      ["displayValue"] = 78,
      ["mode"] = "large",
      ["name"] = "RSSI",
      ["objects"] = {
        ["arc"] = 5,
        ["circle"] = 1,
        ["label"] = 5,
        ["line"] = 18,
        ["total"] = 29,
      },
      ["options"] = {
        ["ShowMinMax"] = "Markers",
      },
      ["orientation"] = "balanced",
      ["radius"] = 69,
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "dial",
      ["showNeedle"] = true,
      ["showScale"] = true,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "dial",
      ["sweep"] = 270,
      ["unit"] = "dB",
      ["value"] = "78",
      ["valueFont"] = 1024,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "220x200",
    },
    ["op-mm-off"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 35,
      ["displayValue"] = 78,
      ["mode"] = "large",
      ["name"] = "RSSI",
      ["objects"] = {
        ["arc"] = 5,
        ["circle"] = 1,
        ["label"] = 5,
        ["line"] = 16,
        ["total"] = 27,
      },
      ["options"] = {
        ["ShowMinMax"] = "Off",
      },
      ["orientation"] = "balanced",
      ["radius"] = 69,
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "dial",
      ["showNeedle"] = true,
      ["showScale"] = true,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "dial",
      ["sweep"] = 270,
      ["unit"] = "dB",
      ["value"] = "78",
      ["valueFont"] = 1024,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "220x200",
    },
    ["op-mm-text"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 35,
      ["displayValue"] = 78,
      ["mode"] = "large",
      ["name"] = "RSSI",
      ["objects"] = {
        ["arc"] = 5,
        ["circle"] = 1,
        ["label"] = 5,
        ["line"] = 18,
        ["total"] = 29,
      },
      ["options"] = {
        ["ShowMinMax"] = "Markers + text",
      },
      ["orientation"] = "balanced",
      ["radius"] = 69,
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "dial",
      ["showNeedle"] = true,
      ["showScale"] = true,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "dial",
      ["sweep"] = 270,
      ["unit"] = "dB",
      ["value"] = "78",
      ["valueFont"] = 1024,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "220x200",
    },
  },
  ["coverage"] = {
    ["Accent"] = "SIN COBERTURA",
    ["AlertSw"] = "n/a",
    ["Alerts"] = "n/a",
    ["Battery"] = "SIN COBERTURA",
    ["Cells"] = "SIN COBERTURA",
    ["ColorMode"] = "SIN COBERTURA",
    ["Crit"] = "SIN COBERTURA",
    ["Damping"] = "SIN COBERTURA",
    ["Delay"] = "n/a",
    ["HighGood"] = "SIN COBERTURA",
    ["Label"] = "SIN COBERTURA",
    ["Max"] = "SIN COBERTURA",
    ["Min"] = "SIN COBERTURA",
    ["Precision"] = "SIN COBERTURA",
    ["ResetSw"] = "n/a",
    ["Scale"] = "SIN COBERTURA",
    ["ShowChip"] = "SIN COBERTURA",
    ["ShowMinMax"] = "Markers,Markers + text,Off",
    ["Style"] = "SIN COBERTURA",
    ["Suffix"] = "SIN COBERTURA",
    ["Sweep"] = "SIN COBERTURA",
    ["Vibrate"] = "n/a",
    ["Warn"] = "SIN COBERTURA",
  },
  ["dirty"] = false,
  ["filter"] = "mm",
  ["generated"] = "2026-08-09 22:35 UTC",
  ["sceneCount"] = 3,
  ["sha"] = "d46102e26",
}
