-- GaugePro gallery manifest - generado por dev/gallery.lua
-- No editar a mano. Comparar con:
--   lua5.3 dev/gallery.lua . --baseline <este fichero>
return {
  ["branch"] = "feat/gauge-v2",
  ["cases"] = {
    ["tx-prec2"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 7,
      ["displayValue"] = 16.62,
      ["mode"] = "normal",
      ["name"] = "RxBt",
      ["objects"] = {
        ["arc"] = 5,
        ["circle"] = 1,
        ["label"] = 3,
        ["line"] = 10,
        ["total"] = 19,
      },
      ["options"] = {
        ["Max"] = "20",
        ["Min"] = "0",
        ["Precision"] = "2",
        ["Scale"] = "Manual",
      },
      ["orientation"] = "balanced",
      ["radius"] = 52,
      ["scaleMax"] = 20,
      ["scaleMin"] = 0,
      ["section"] = "texto",
      ["showNeedle"] = true,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "dial",
      ["sweep"] = 270,
      ["unit"] = "V",
      ["value"] = "16.62",
      ["valueFont"] = 768,
      ["warn"] = 11,
      ["warnings"] = 0,
      ["zone"] = "200x160",
    },
    ["tx-prec2-micro"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 7,
      ["displayValue"] = 16.62,
      ["mode"] = "micro",
      ["name"] = "RxBt",
      ["objects"] = {
        ["arc"] = 4,
        ["label"] = 1,
        ["line"] = 3,
        ["total"] = 8,
      },
      ["options"] = {
        ["Max"] = "20",
        ["Min"] = "0",
        ["Precision"] = "2",
        ["Scale"] = "Manual",
      },
      ["orientation"] = "balanced",
      ["radius"] = 21,
      ["scaleMax"] = 20,
      ["scaleMin"] = 0,
      ["section"] = "texto",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = false,
      ["state"] = "normal",
      ["style"] = "dial",
      ["sweep"] = 270,
      ["unit"] = "V",
      ["value"] = "16.62",
      ["valueFont"] = 512,
      ["warn"] = 11,
      ["warnings"] = 0,
      ["zone"] = "60x60",
    },
  },
  ["coverage"] = {
    ["Accent"] = "SIN COBERTURA",
    ["AlertSw"] = "n/a",
    ["Alerts"] = "n/a",
    ["Battery"] = "SIN COBERTURA",
    ["Cells"] = "SIN COBERTURA",
    ["ColorMode"] = "SIN COBERTURA",
    ["Crit"] = "SIN COBERTURA",
    ["Damping"] = "SIN COBERTURA",
    ["Delay"] = "n/a",
    ["HighGood"] = "SIN COBERTURA",
    ["Label"] = "SIN COBERTURA",
    ["Max"] = "20",
    ["Min"] = "0",
    ["Precision"] = "2",
    ["ResetSw"] = "n/a",
    ["Scale"] = "Manual",
    ["ShowChip"] = "SIN COBERTURA",
    ["ShowMinMax"] = "SIN COBERTURA",
    ["Style"] = "SIN COBERTURA",
    ["Suffix"] = "SIN COBERTURA",
    ["Sweep"] = "SIN COBERTURA",
    ["Vibrate"] = "n/a",
    ["Warn"] = "SIN COBERTURA",
  },
  ["dirty"] = false,
  ["filter"] = "prec2",
  ["generated"] = "2026-08-09 22:29 UTC",
  ["sceneCount"] = 2,
  ["sha"] = "d46102e26",
}
