-- GaugePro gallery manifest - generado por dev/gallery.lua
-- No editar a mano. Comparar con:
--   lua5.3 dev/gallery.lua . --baseline <este fichero>
return {
  ["branch"] = "feat/gauge-v2",
  ["cases"] = {
    ["br-auto"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 35,
      ["displayValue"] = 78,
      ["mode"] = "micro",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 3,
        ["line"] = 4,
        ["rectangle"] = 2,
        ["total"] = 9,
      },
      ["options"] = {
        ["Style"] = "Auto",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "78",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x60",
    },
    ["br-crit"] = {
      ["availability"] = "valid",
      ["chip"] = "CRIT",
      ["colorKey"] = "critical",
      ["crit"] = 35,
      ["displayValue"] = 22,
      ["mode"] = "compact",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 4,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 12,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "critical",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "22",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x70",
    },
    ["br-lowgood"] = {
      ["availability"] = "valid",
      ["chip"] = "CRIT",
      ["colorKey"] = "critical",
      ["crit"] = 90,
      ["displayValue"] = 95,
      ["mode"] = "compact",
      ["name"] = "T1",
      ["objects"] = {
        ["label"] = 4,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 12,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 120,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "critical",
      ["style"] = "bar",
      ["unit"] = "C",
      ["value"] = "95",
      ["valueFont"] = 512,
      ["warn"] = 70,
      ["warnings"] = 0,
      ["zone"] = "300x70",
    },
    ["br-narrow"] = {
      ["availability"] = "valid",
      ["chip"] = "CRIT",
      ["colorKey"] = "critical",
      ["crit"] = 35,
      ["displayValue"] = 22,
      ["mode"] = "micro",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 3,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 11,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "critical",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "22",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x44",
    },
    ["br-nochip"] = {
      ["availability"] = "valid",
      ["chip"] = "CRIT",
      ["colorKey"] = "critical",
      ["crit"] = 35,
      ["displayValue"] = 22,
      ["mode"] = "compact",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 4,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 12,
      },
      ["options"] = {
        ["ShowChip"] = "false",
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "critical",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "22",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x70",
    },
    ["br-normal"] = {
      ["availability"] = "valid",
      ["chip"] = "",
      ["colorKey"] = "normal",
      ["crit"] = 35,
      ["displayValue"] = 78,
      ["mode"] = "compact",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 3,
        ["line"] = 4,
        ["rectangle"] = 2,
        ["total"] = 9,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "normal",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "78",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x70",
    },
    ["br-short"] = {
      ["availability"] = "valid",
      ["chip"] = "CRIT",
      ["colorKey"] = "critical",
      ["crit"] = 35,
      ["displayValue"] = 22,
      ["mode"] = "micro",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 3,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 11,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "critical",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "22",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "160x44",
    },
    ["br-warn"] = {
      ["availability"] = "valid",
      ["chip"] = "WARN",
      ["colorKey"] = "warning",
      ["crit"] = 35,
      ["displayValue"] = 45,
      ["mode"] = "compact",
      ["name"] = "RSSI",
      ["objects"] = {
        ["label"] = 4,
        ["line"] = 4,
        ["rectangle"] = 4,
        ["total"] = 12,
      },
      ["options"] = {
        ["Style"] = "Bar",
      },
      ["orientation"] = "horizontal",
      ["scaleMax"] = 100,
      ["scaleMin"] = 0,
      ["section"] = "barra",
      ["showNeedle"] = false,
      ["showScale"] = false,
      ["showState"] = true,
      ["state"] = "warning",
      ["style"] = "bar",
      ["unit"] = "dB",
      ["value"] = "45",
      ["valueFont"] = 512,
      ["warn"] = 55,
      ["warnings"] = 0,
      ["zone"] = "300x70",
    },
  },
  ["coverage"] = {
    ["Accent"] = "SIN COBERTURA",
    ["AlertSw"] = "n/a",
    ["Alerts"] = "n/a",
    ["Battery"] = "SIN COBERTURA",
    ["Cells"] = "SIN COBERTURA",
    ["ColorMode"] = "SIN COBERTURA",
    ["Crit"] = "SIN COBERTURA",
    ["Damping"] = "SIN COBERTURA",
    ["Delay"] = "n/a",
    ["HighGood"] = "SIN COBERTURA",
    ["Label"] = "SIN COBERTURA",
    ["Max"] = "SIN COBERTURA",
    ["Min"] = "SIN COBERTURA",
    ["Precision"] = "SIN COBERTURA",
    ["ResetSw"] = "n/a",
    ["Scale"] = "SIN COBERTURA",
    ["ShowChip"] = "false",
    ["ShowMinMax"] = "SIN COBERTURA",
    ["Style"] = "Auto,Bar",
    ["Suffix"] = "SIN COBERTURA",
    ["Sweep"] = "SIN COBERTURA",
    ["Vibrate"] = "n/a",
    ["Warn"] = "SIN COBERTURA",
  },
  ["dirty"] = false,
  ["filter"] = "barra",
  ["generated"] = "2026-08-09 22:37 UTC",
  ["sceneCount"] = 8,
  ["sha"] = "d46102e26",
}
