"""Generates docs/visual-kit/{CATALOG.md,INDEX.md,RUN_SUMMARY.md} from
run.log.jsonl -- the SAME record generate/capture already produced, so the
docs can never describe a screen that wasn't actually captured (plan Sec 13:
"come from the same source of truth so they do not become inconsistent").
"""

import json
import os
import time

from verify_dupes import find_duplicate_groups


def load_runlog(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _fmt_zone(row):
    """The REAL (LayoutId, zone_index) -> WxH px a screen rendered into, when
    known -- docs/visual-kit/INFORME-DEFECTOS.md H-01: CATALOG.md used to say
    nothing about the zone a screen was captured at, which is exactly the
    fact that would have caught the harness ignoring every case's declared
    `zone` and rendering fullscreen instead."""
    rect = row.get("zone_rect")
    if not rect:
        return ""
    _x, _y, w, h = rect
    layout = row.get("layout") or ""
    zi = row.get("zone_index")
    zi_s = ("z%d" % zi) if zi is not None else ""
    return "%dx%d (%s %s)" % (w, h, layout, zi_s)


def _fmt_overrides(overrides):
    if not overrides:
        return ""
    # Only the keys the plan's remap machinery didn't inject verbatim are
    # interesting to a reader; Source/Min/Max/Warn/Crit are voltage_window()
    # artifacts (see catalog.py), not the scene's authored intent.
    skip = {"Source"}
    parts = []
    for k, v in overrides.items():
        if k in skip:
            continue
        parts.append("%s=%s" % (k, v))
    return ", ".join(parts)


def flag_cross_case_duplicates(rows, shots_dir):
    """Downgrades PASS -> WARN in place for any row whose screenshot is
    byte-identical to a DIFFERENT case's screenshot.

    docs/visual-kit/INFORME-DEFECTOS.md H-01 remediation #3: a duplicate
    across cases with different names is either the batch-boundary reset
    race verify_dupes.py's docstring describes, or (the class this was
    actually catching before it was wired in here) the harness silently
    defeating the point of one or both cases -- e.g. four different bar
    cases rendering at the same wrong fullscreen size instead of their own
    declared zone. Either way that is not a PASS. A duplicate group where
    every screenshot belongs to the SAME case (a theme capture identical to
    its stock baseline, H-03) is left alone -- expected, not a defect.

    So is a group EXPECTED_IDENTICAL explains: "Medium IS the default
    thickness" is not a finding, and burying the real ones among 48 of those
    is the same as reporting none. Three genuine defects (a shared option
    with no effect, a surface that painted nothing, three dial colour modes
    collapsed into one) sat in that undifferentiated list for a whole run
    before the triage was added -- see verify_dupes.classify_group."""
    groups = find_duplicate_groups(shots_dir, only_unexpected=True)
    by_file = {r["file"]: r for r in rows if r.get("file")}
    for files in groups.values():
        present = [by_file[f] for f in files if f in by_file]
        if len({r["name"] for r in present}) <= 1:
            continue
        for r in present:
            if r.get("status") != "PASS":
                continue
            r["status"] = "WARN"
            r["warn_reason"] = "byte-identical to %s" % ", ".join(
                f for f in files if f != r["file"])


def write_catalog_md(path, rows, skipped):
    lines = []
    lines.append("# Gauge Dial Pro + Gauge Bar Pro Visual Kit -- Catalog")
    lines.append("")
    lines.append("Generated by `tools/gaugepro-visual-kit/run.py`. "
                  "Do not hand-edit -- rerun `python run.py all` instead.")
    lines.append("")
    lines.append("Current split contract: `DialPro` and `BarPro` over shared `GaugeCore`.")
    lines.append("")

    sections = {}
    for r in rows:
        if r.get("status") == "SKIP":
            continue
        sections.setdefault(r["section"], []).append(r)

    for section, items in sections.items():
        lines.append("## %s" % section)
        lines.append("")
        lines.append("| # | Case | Widget | Status | Options (non-default) | Zone (real) | Screenshot |")
        lines.append("|---:|---|---|---|---|---|---|")
        for r in items:
            seq = r.get("seq")
            seq_s = ("%03d" % seq) if seq is not None else ""
            opts = _fmt_overrides(r.get("overrides") or {})
            zone = _fmt_zone(r)
            title = r.get("title") or r["name"]
            img = ("[%s](screenshots/%s)" % (r["file"], r["file"])) if r.get("file") else ""
            lines.append("| %s | %s | %s | %s | %s | %s | %s |"
                          % (seq_s, title, r.get("widget", ""), r["status"],
                             opts, zone, img))
        lines.append("")

    if skipped:
        lines.append("## Skipped (this pass)")
        lines.append("")
        lines.append("| Case | Reason |")
        lines.append("|---|---|")
        for name, reason in skipped.items():
            lines.append("| %s | %s |" % (name, reason))
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_index_md(path, rows):
    lines = []
    lines.append("# Gauge Dial Pro + Gauge Bar Pro Visual Kit -- Gallery")
    lines.append("")
    lines.append("Generated by `tools/gaugepro-visual-kit/run.py`. "
                  "See [CATALOG.md](CATALOG.md) for the full option-by-option index.")
    lines.append("")

    sections = {}
    order = []
    for r in rows:
        if r.get("status") != "PASS" or not r.get("file"):
            continue
        if r["section"] not in sections:
            order.append(r["section"])
        sections.setdefault(r["section"], []).append(r)

    for section in order:
        lines.append("## %s" % section)
        lines.append("")
        for r in sections[section]:
            title = r.get("title") or r["name"]
            lines.append('<img src="screenshots/%s" width="240" alt="%s" title="%s">'
                         % (r["file"], title, title))
        lines.append("")
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_run_summary(path, rows, simu_build=""):
    total = sum(1 for r in rows if r.get("status") in ("PASS", "WARN", "FAIL"))
    passed = sum(1 for r in rows if r.get("status") == "PASS")
    warned = sum(1 for r in rows if r.get("status") == "WARN")
    failed = sum(1 for r in rows if r.get("status") == "FAIL")
    skipped = sum(1 for r in rows if r.get("status") == "SKIP")
    dial = sum(1 for r in rows if r.get("family") == "dial" and
               r.get("status") in ("PASS", "WARN", "FAIL"))
    bar = sum(1 for r in rows if r.get("family") == "bar" and
              r.get("status") in ("PASS", "WARN", "FAIL"))
    mixed = sum(1 for r in rows if r.get("family") == "mixed" and
                r.get("status") in ("PASS", "WARN", "FAIL"))

    lines = []
    lines.append("# Gauge Dial Pro + Gauge Bar Pro Visual Kit -- Last Run Summary")
    lines.append("")
    lines.append("- Generated: %s" % time.strftime("%Y-%m-%d %H:%M:%S"))
    if simu_build:
        lines.append("- simu build: %s" % simu_build)
    lines.append("- Screens captured: **%d**" % total)
    lines.append("- Families: DialPro %d, BarPro %d, mixed layouts %d" %
                 (dial, bar, mixed))
    lines.append("- Pass: %d" % passed)
    lines.append("- Warn: %d" % warned)
    lines.append("- Fail: %d" % failed)
    lines.append("- Skipped (documented, see CATALOG.md): %d" % skipped)
    lines.append("")
    if failed:
        lines.append("## Failures")
        lines.append("")
        for r in rows:
            if r.get("status") == "FAIL":
                lines.append("- %s (%s): %s" % (r["name"], r.get("section", ""),
                                                 r.get("error", "capture failed")))
        lines.append("")

    if warned:
        lines.append("## Warnings")
        lines.append("")
        for r in rows:
            if r.get("status") == "WARN":
                lines.append("- %s (%s): %s" % (r["name"], r.get("section", ""),
                                                 r.get("warn_reason", "")))
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
