"""Generates docs/visual-kit/{CATALOG.md,INDEX.md,RUN_SUMMARY.md} from
run.log.jsonl -- the SAME record generate/capture already produced, so the
docs can never describe a screen that wasn't actually captured (plan Sec 13:
"come from the same source of truth so they do not become inconsistent").
"""

import json
import os
import time


def load_runlog(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _fmt_overrides(overrides):
    if not overrides:
        return ""
    # Only the keys the plan's remap machinery didn't inject verbatim are
    # interesting to a reader; Source/Min/Max/Warn/Crit are voltage_window()
    # artifacts (see catalog.py), not the scene's authored intent.
    skip = {"Source"}
    parts = []
    for k, v in overrides.items():
        if k in skip:
            continue
        parts.append("%s=%s" % (k, v))
    return ", ".join(parts)


def write_catalog_md(path, rows, skipped):
    lines = []
    lines.append("# Gauge Pro Visual Kit -- Catalog")
    lines.append("")
    lines.append("Generated by `tools/gaugepro-visual-kit/run.py`. "
                  "Do not hand-edit -- rerun `python run.py all` instead.")
    lines.append("")

    sections = {}
    for r in rows:
        if r.get("status") == "SKIP":
            continue
        sections.setdefault(r["section"], []).append(r)

    for section, items in sections.items():
        lines.append("## %s" % section)
        lines.append("")
        lines.append("| # | Case | Status | Options (non-default) | Screenshot |")
        lines.append("|---:|---|---|---|---|")
        for r in items:
            seq = r.get("seq")
            seq_s = ("%03d" % seq) if seq is not None else ""
            opts = _fmt_overrides(r.get("overrides") or {})
            title = r.get("title") or r["name"]
            img = ("[%s](screenshots/%s)" % (r["file"], r["file"])) if r.get("file") else ""
            lines.append("| %s | %s | %s | %s | %s |"
                          % (seq_s, title, r["status"], opts, img))
        lines.append("")

    if skipped:
        lines.append("## Skipped (this pass)")
        lines.append("")
        lines.append("| Case | Reason |")
        lines.append("|---|---|")
        for name, reason in skipped.items():
            lines.append("| %s | %s |" % (name, reason))
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_index_md(path, rows):
    lines = []
    lines.append("# Gauge Pro Visual Kit -- Gallery")
    lines.append("")
    lines.append("Generated by `tools/gaugepro-visual-kit/run.py`. "
                  "See [CATALOG.md](CATALOG.md) for the full option-by-option index.")
    lines.append("")

    sections = {}
    order = []
    for r in rows:
        if r.get("status") != "PASS" or not r.get("file"):
            continue
        if r["section"] not in sections:
            order.append(r["section"])
        sections.setdefault(r["section"], []).append(r)

    for section in order:
        lines.append("## %s" % section)
        lines.append("")
        for r in sections[section]:
            title = r.get("title") or r["name"]
            lines.append('<img src="screenshots/%s" width="240" alt="%s" title="%s">'
                         % (r["file"], title, title))
        lines.append("")
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_run_summary(path, rows, simu_build=""):
    total = sum(1 for r in rows if r.get("status") in ("PASS", "WARN", "FAIL"))
    passed = sum(1 for r in rows if r.get("status") == "PASS")
    warned = sum(1 for r in rows if r.get("status") == "WARN")
    failed = sum(1 for r in rows if r.get("status") == "FAIL")
    skipped = sum(1 for r in rows if r.get("status") == "SKIP")

    lines = []
    lines.append("# Gauge Pro Visual Kit -- Last Run Summary")
    lines.append("")
    lines.append("- Generated: %s" % time.strftime("%Y-%m-%d %H:%M:%S"))
    if simu_build:
        lines.append("- simu build: %s" % simu_build)
    lines.append("- Screens captured: **%d**" % total)
    lines.append("- Pass: %d" % passed)
    lines.append("- Warn: %d" % warned)
    lines.append("- Fail: %d" % failed)
    lines.append("- Skipped (documented, see CATALOG.md): %d" % skipped)
    lines.append("")
    if failed:
        lines.append("## Failures")
        lines.append("")
        for r in rows:
            if r.get("status") == "FAIL":
                lines.append("- %s (%s): %s" % (r["name"], r.get("section", ""),
                                                 r.get("error", "capture failed")))
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
