# Copy the GaugePro runtime payload to an SD-card folder (radio or simulator).
#
#   pwsh dev/sync-sd.ps1                       # -> D:\SD\WIDGETS\GaugePro
#   pwsh dev/sync-sd.ps1 -Destination E:\      # -> E:\WIDGETS\GaugePro
#
# Only the runtime modules are copied: tests/ and dev/ have no business on a
# radio, and stale copies there make it hard to tell which version is running.

param(
  [string]$Destination = "D:\SD"
)

$source = [System.IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$destinationPath = [System.IO.Path]::GetFullPath($Destination)
$target = [System.IO.Path]::GetFullPath(
  (Join-Path $destinationPath "WIDGETS\GaugePro"))

$expectedSuffix = [System.IO.Path]::Combine("WIDGETS", "GaugePro")
if (-not $target.EndsWith($expectedSuffix,
    [System.StringComparison]::OrdinalIgnoreCase)) {
  throw "refusing unsafe target: $target"
}

$runtimeRequired = @(
  "main.lua", "app.lua", "options.lua", "theme.lua", "geometry.lua",
  "ranges.lua", "presets.lua", "format.lua", "smoothing.lua",
  "motion.lua", "telemetry.lua", "layout.lua", "renderer.lua", "bar_style.lua",
  "bar_faces.lua", "bar.lua", "alerts.lua"
)

$runtime = @($runtimeRequired)

New-Item -ItemType Directory -Force -Path $target | Out-Null

# EdgeTX may prefer a compiled sibling over the edited source. Remove only
# generated bytecode directly inside the exact GaugePro target before copy;
# never recurse into the destination or touch another widget.
$staleBytecode = @(Get-ChildItem -LiteralPath $target -Filter "*.luac" -File)
foreach ($file in $staleBytecode) {
  Remove-Item -LiteralPath $file.FullName -Force
}

$copied = 0
foreach ($f in $runtime) {
  $src = Join-Path $source $f
  if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
    throw "missing runtime module: $f"
  }
  Copy-Item -LiteralPath $src -Destination (Join-Path $target $f) -Force
  $copied++
}
foreach ($doc in @("DOCS.md", "README.md")) {
  $src = Join-Path $source $doc
  if (Test-Path -LiteralPath $src -PathType Leaf) {
    Copy-Item -LiteralPath $src -Destination (Join-Path $target $doc) -Force
  }
}

$kb = [math]::Round(((Get-ChildItem -LiteralPath $target -File |
  Measure-Object Length -Sum).Sum / 1KB), 1)
Write-Host "GaugePro -> $target  ($copied modules, $kb KB, $($staleBytecode.Count) stale .luac removed)"
